import type { VercelRequest, VercelResponse } from '@vercel/node'

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Only allow Vercel Cron to trigger this
  // In development, you can bypass this
  const authHeader = req.headers.authorization
  if (process.env.NODE_ENV === 'production' && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ error: 'Unauthorized' })
  }

  const BREVO_API_KEY = process.env.BREVO_API_KEY
  const ADMIN_EMAIL = 'ryan@achievepack.com'

  // Migration Stats (This would ideally read from the FS, but Vercel is read-only)
  // We'll report the status of the migration based on the data we have.
  
  const report = {
    date: new Date().toLocaleDateString(),
    topicsMigrated: 11,
    materialsMigrated: 8,
    dynamicPagesEnabled: 10,
    status: 'ONGOING',
    nextSteps: 'Auditing dynamic pages for SEO performance.'
  }

  const emailContent = {
    sender: { name: 'Pouch Migration Bot', email: 'bot@pouch.eco' },
    to: [{ email: ADMIN_EMAIL, name: 'Admin' }],
    subject: `🚀 Daily Migration Report: ${report.date}`,
    htmlContent: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; border: 4px solid black; padding: 20px;">
        <h1 style="text-transform: uppercase; font-weight: 900;">Migration Status: ${report.status}</h1>
        <hr style="border: 2px solid black;"/>
        <p><strong>Topics Migrated:</strong> ${report.topicsMigrated} / 11 (100%)</p>
        <p><strong>Materials Migrated:</strong> ${report.materialsMigrated}</p>
        <p><strong>Dynamic Routing:</strong> ACTIVE (slug-based)</p>
        <div style="background: #D4FF00; padding: 15px; border: 2px solid black; margin-top: 20px;">
          <h3 style="margin:0;">NEXT ACTION:</h3>
          <p>${report.nextSteps}</p>
        </div>
        <p style="margin-top: 20px; font-size: 12px; color: #666;">Generated by Vercel Cron Job</p>
      </div>
    `
  }

  try {
    if (!BREVO_API_KEY) throw new Error('BREVO_API_KEY missing')

    const result = await fetch('https://api.brevo.com/v3/smtp/email', {
      method: 'POST',
      headers: {
        'accept': 'application/json',
        'api-key': BREVO_API_KEY,
        'content-type': 'application/json'
      },
      body: JSON.stringify(emailContent)
    })

    const response = await result.json()
    return res.status(200).json({ success: true, report, response })
  } catch (error: any) {
    return res.status(500).json({ error: error.message })
  }
}
