import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { Loader2, AlertCircle, FileText, Download } from 'lucide-react';
import { Helmet } from 'react-helmet-async';

const SharedQuotePage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [quoteHtml, setQuoteHtml] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchQuote = async () => {
      if (!id) return;
      
      try {
        const response = await fetch(`/api/get-shared-quote?id=${id}`);
        const data = await response.json();

        if (!response.ok || !data.success) {
          throw new Error(data.error || 'Quote content not found. This link may be broken or expired.');
        }

        if (!data.quoteHtml) {
          throw new Error('Quote content is empty.');
        }

        setQuoteHtml(data.quoteHtml);
      } catch (err: any) {
        console.error('Error fetching shared quote:', err);
        setError(err.message || 'Failed to load quotation');
      } finally {
        setLoading(false);
      }
    };

    fetchQuote();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-4">
        <Loader2 className="w-12 h-12 text-blue-600 animate-spin mb-4" />
        <p className="text-gray-600 font-bold">Securely loading quotation...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-4 text-center">
        <div className="bg-white p-8 rounded-3xl shadow-xl border border-red-100 max-w-md">
          <AlertCircle className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h1 className="text-2xl font-black text-gray-900 mb-2">Quotation Error</h1>
          <p className="text-gray-600 mb-6">{error}</p>
          <a href="/" className="inline-block bg-gray-900 text-white px-6 py-3 rounded-xl font-bold hover:bg-black transition">
            Go to Homepage
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-100 font-sans">
      <Helmet>
        <title>Official Quotation | Achieve Pack</title>
      </Helmet>

      {/* Action Bar (Not shown in print) */}
      <div className="bg-white border-b border-gray-200 px-6 py-3 sticky top-0 z-50 print:hidden shadow-sm">
        <div className="max-w-5xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-3">
            <img src="/logo.png" alt="Achieve Pack" className="h-8 w-auto" />
            <span className="h-4 w-px bg-gray-300 mx-1"></span>
            <span className="text-sm font-bold text-gray-700 uppercase tracking-wider flex items-center gap-2">
              <FileText className="w-4 h-4 text-blue-600" /> Secure Quotation Hub
            </span>
          </div>
          <button 
            onClick={() => window.print()}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-2 rounded-lg font-bold shadow-md transition active:scale-95"
          >
            <Download className="w-4 h-4" /> Save as PDF / Print
          </button>
        </div>
      </div>

      <div className="max-w-5xl mx-auto py-8 sm:py-12 px-4 sm:px-6">
        <div className="bg-white shadow-2xl rounded-3xl overflow-hidden border border-gray-200 ring-1 ring-black/5">
          {quoteHtml && (
            <iframe 
              srcDoc={quoteHtml} 
              className="w-full border-none min-h-[1100px]" 
              title="Official Quotation"
              style={{ display: 'block' }}
            />
          )}
        </div>
        
        <div className="mt-8 text-center text-gray-500 text-xs print:hidden">
          <p>© {new Date().getFullYear()} Achieve Pack Limited. All rights reserved.</p>
          <p className="mt-1">This is an official document generated by Achieve Pack Secure Document Hub.</p>
        </div>
      </div>

      <style>{`
        @media print {
          @page { margin: 0; }
          body { background: white; padding: 0; margin: 0; }
          .min-h-screen { min-height: 0 !important; background: white !important; }
          .max-w-5xl { max-width: none !important; width: 100% !important; padding: 0 !important; margin: 0 !important; }
          .bg-gray-100 { background: white !important; }
          .rounded-3xl { border-radius: 0 !important; border: none !important; }
          .shadow-2xl { shadow: none !important; }
          iframe { width: 100% !important; height: auto !important; min-height: 297mm !important; }
        }
      `}</style>
    </div>
  );
};

export default SharedQuotePage;
