export const translations = {
  "appHome.string_1": { en: "English", es: "Inglés", fr: "Anglais", "zh-TW": "英文" },
  "appHome.string_2": { en: "Français", es: "Francés", fr: "Français", "zh-TW": "法文" },
  "appHome.string_3": { en: "Español", es: "Español", fr: "Espagnol", "zh-TW": "西班牙文" },
  "appHome.string_4": { en: "EN", es: "EN", fr: "EN", "zh-TW": "英" },
  "appHome.string_5": { en: "FR", es: "FR", fr: "FR", "zh-TW": "法" },
  "appHome.string_6": { en: "ES", es: "ES", fr: "ES", "zh-TW": "西" },
  "appHome.string_7": { en: "📅 Book Free Consultation", es: "📅 Reservar Consulta Gratuita", fr: "📅 Réserver une Consultation", "zh-TW": "📅 預約免費諮詢" },
  "appHome.string_8": { en: "Compostable OK", es: "Compostable OK", fr: "Compostable OK", "zh-TW": "全降解 OK" },
  "appHome.string_9": { en: "Recyclable OK", es: "Reciclable OK", fr: "Recyclable OK", "zh-TW": "可回收 OK" },
  "appHome.string_10": { en: "Industrial OK", es: "Industrial OK", fr: "Industriel OK", "zh-TW": "工業降解 OK" },
  "appHome.string_11": { en: "PCR Barrier OK", es: "Barrera PCR OK", fr: "Barrière PCR OK", "zh-TW": "PCR 阻隔 OK" },
  "appHome.string_12": { en: "Bio-based OK", es: "Basado en bio OK", fr: "Biosourcé OK", "zh-TW": "生物基 OK" },
  "appHome.string_13": { en: "MOQ 500!", es: "¡MOQ 500!", fr: "MOQ 500 !", "zh-TW": "起訂量 500！" },
  "appHome.string_14": { en: "Compostable", es: "Compostable", fr: "Compostable", "zh-TW": "全降解" },
  "appHome.string_15": { en: "Recyclable", es: "Reciclable", fr: "Recyclable", "zh-TW": "可回收" },
  "appHome.string_16": { en: "PCR", es: "PCR", fr: "PCR", "zh-TW": "PCR" },
  "appHome.string_17": { en: "Bio-PE", es: "Bio-PE", fr: "Bio-PE", "zh-TW": "生物基 PE" },
  "appHome.string_18": { en: "Home Compost Certification", es: "Certificación de Compostaje Doméstico", fr: "Certification de Compostage Domestique", "zh-TW": "家庭堆肥認證" },
  "appHome.string_19": { en: "PCR GRS Certification", es: "Certificación PCR GRS", fr: "Certification PCR GRS", "zh-TW": "PCR GRS 認證" },
  "appHome.string_20": { en: "BRC Food Safety Certification", es: "Certificación de Seguridad Alimentaria BRC", fr: "Certification de Sécurité Alimentaire BRC", "zh-TW": "BRC 食品安全認證" },
  "appHome.string_21": { en: "BioPE Sustainable Certification", es: "Certificación Sostenible BioPE", fr: "Certification Durable BioPE", "zh-TW": "BioPE 可持續認證" },
  "appHome.string_22": { en: "EN13432", es: "EN13432", fr: "EN13432", "zh-TW": "EN13432" },
  "appHome.string_23": { en: "ASTM D6400", es: "ASTM D6400", fr: "ASTM D6400", "zh-TW": "ASTM D6400" },
  "appHome.string_24": { en: "Compostable packaging lifecycle - from plant-based materials to soil nutrients", es: "Ciclo de vida del empaque compostable: de materiales a base de plantas a nutrientes del suelo", fr: "Cycle de vie des emballages compostables : des matériaux d'origine végétale aux nutriments du sol", "zh-TW": "全降解包裝生命週期 - 從植物基材料到土壤養分" },
  "appHome.string_25": { en: "Food & Beverage Packaging", es: "Empaque de Alimentos y Bebidas", fr: "Emballage pour Aliments et Boissons", "zh-TW": "食品與飲料包裝" },
  "appHome.string_26": { en: "View Profile", es: "Ver Perfil", fr: "Voir le Profil", "zh-TW": "查看個人資料" },
  "appHome.string_27": { en: ": ryan@achievepack.com", es: ": ryan@achievepack.com", fr: ": ryan@achievepack.com", "zh-TW": ": ryan@achievepack.com" },
  "appHome.string_28": { en: "Certified B Corporation", es: "Empresa B Certificada", fr: "Entreprise B Certifiée", "zh-TW": "B 型企業認證" },
  "appHome.string_29": { en: "BPI Certified", es: "Certificado BPI", fr: "Certifié BPI", "zh-TW": "BPI 認證" },
  "appHome.string_30": { en: "New", es: "Nuevo", fr: "Nouveau", "zh-TW": "最新" },
  "appHome.string_31": { en: "🇺🇸 USA", es: "🇺🇸 EE. UU.", fr: "🇺🇸 États-Unis", "zh-TW": "🇺🇸 美國" },
  "appHome.string_32": { en: "Compostable Hub", es: "Centro de Compostables", fr: "Hub Compostable", "zh-TW": "全降解中心" },
  "appHome.string_33": { en: "Coffee Packaging", es: "Empaque para Café", fr: "Emballage pour Café", "zh-TW": "咖啡包裝" },
  "appHome.string_34": { en: "Snacks Packaging", es: "Empaque para Snacks", fr: "Emballage pour Snacks", "zh-TW": "零食包裝" },
  "appHome.string_35": { en: "Labeling Guide", es: "Guía de Etiquetado", fr: "Guide d'Étiquetage", "zh-TW": "標籤指南" },
  "appHome.string_36": { en: "Product Guides", es: "Guías de Productos", fr: "Guides de Produits", "zh-TW": "產品指南" },
  "appHome.string_37": { en: "Compostable Coffee Bags", es: "Bolsas de Café Compostables", fr: "Sacs à Café Compostables", "zh-TW": "全降解咖啡袋" },
  "appHome.string_38": { en: "Compostable Side Gusset", es: "Fuelle Lateral Compostable", fr: "Soufflet Latéral Compostable", "zh-TW": "全降解側邊風琴袋" },
  "appHome.string_39": { en: "Compostable Stand-Up", es: "Bolsa Stand-Up Compostable", fr: "Sachet Stand-Up Compostable", "zh-TW": "全降解自立袋" },
  "appHome.string_40": { en: "Recyclable Mono-Material", es: "Monomaterial Reciclable", fr: "Mono-Matériau Recyclable", "zh-TW": "可回收單一材質" },
  "appHome.string_41": { en: "Coffee Degassing Valve", es: "Válvula Desgasificadora de Café", fr: "Valve de Dégazage pour Café", "zh-TW": "咖啡排氣閥" },
  "appHome.string_42": { en: "Low MOQ Packaging", es: "Empaque de Bajo MOQ", fr: "Emballage à Faible MOQ", "zh-TW": "低起訂量包裝" },
  "appHome.string_43": { en: "Solutions", es: "Soluciones", fr: "Solutions", "zh-TW": "解決方案" },
  "appHome.string_44": { en: "For Startups", es: "Para Startups", fr: "Pour Startups", "zh-TW": "為初創企業" },
  "appHome.string_45": { en: "For E-commerce", es: "Para Comercio Electrónico", fr: "Pour l'E-commerce", "zh-TW": "為電子商務" },
  "appHome.string_46": { en: "For Coffee Roasters", es: "Para Tostadores de Café", fr: "Pour Torréfacteurs de Café", "zh-TW": "為咖啡烘焙商" },
  "appHome.string_47": { en: "For Artisan Makers", es: "Para Creadores Artesanales", fr: "Pour Artisans", "zh-TW": "為手工品牌" },
  "appHome.string_48": { en: "For Snack Brands", es: "Para Marcas de Snacks", fr: "Pour Marques de Snacks", "zh-TW": "為零食品牌" },
  "appHome.string_49": { en: "For Corporate ESG", es: "Para ESG Corporativo", fr: "Pour ESG d'Entreprise", "zh-TW": "為企業 ESG" },
  "appHome.string_50": { en: "For Food Manufacturers", es: "Para Fabricantes de Alimentos", fr: "Pour Fabricants de Produits Alimentaires", "zh-TW": "為食品製造商" },
  "appHome.string_51": { en: "For Product Developers", es: "Para Desarrolladores de Productos", fr: "Pour Développeurs de Produits", "zh-TW": "為產品開發者" },
  "appHome.string_52": { en: "Topics", es: "Temas", fr: "Thèmes", "zh-TW": "主題" },
  "appHome.string_53": { en: "Eco Food Packaging", es: "Empaque Ecológico de Alimentos", fr: "Emballage Alimentaire Éco", "zh-TW": "環保食品包裝" },
  "appHome.string_54": { en: "DTC Packaging", es: "Empaque DTC", fr: "Emballage DTC", "zh-TW": "DTC 包裝" },
  "appHome.string_55": { en: "Coffee Materials", es: "Materiales de Café", fr: "Matériaux pour Café", "zh-TW": "咖啡材料" },
  "appHome.string_56": { en: "Digital Printing", es: "Impresión Digital", fr: "Impression Numérique", "zh-TW": "數位印刷" },
  "appHome.string_57": { en: "Recyclable Snacks", es: "Snacks Reciclables", fr: "Snacks Recyclables", "zh-TW": "可回收零食包裝" },
  "appHome.string_58": { en: "Regulations Guide", es: "Guía de Regulaciones", fr: "Guide des Réglementations", "zh-TW": "法規指南" },
  "appHome.string_59": { en: "Compostable Suppliers", es: "Proveedores Compostables", fr: "Fournisseurs Compostables", "zh-TW": "全降解供應商" },
  "appHome.string_60": { en: "Low MOQ Startup", es: "Startup Bajo MOQ", fr: "Startup à Faible MOQ", "zh-TW": "低起訂量初創企業" },
  "appHome.string_61": { en: "Baby Food Bags", es: "Bolsas de Comida para Bebés", fr: "Sacs de Nourriture pour Bébés", "zh-TW": "嬰兒食品袋" },
  "appHome.string_62": { en: "Custom Printed Pouches", es: "Bolsas Impresas Personalizadas", fr: "Sachets Imprimés sur Mesure", "zh-TW": "客製化印刷袋" },
  "appHome.string_63": { en: "Zipper Durability", es: "Durabilidad de la Cremallera", fr: "Durabilité de la Fermeture Éclair", "zh-TW": "夾鏈耐用性" },
  "appHome.string_64": { en: "Custom vs. Standard", es: "Personalizado vs. Estándar", fr: "Personnalisé vs Standard", "zh-TW": "客製化 vs 標準包裝" },
  "appHome.string_65": { en: "Function", es: "Función", fr: "Fonction", "zh-TW": "功能" },
  "appHome.string_66": { en: "Microwave Steam Bags", es: "Bolsas de Vapor para Microondas", fr: "Sacs Vapeur pour Micro-ondes", "zh-TW": "微波蒸煮袋" },
  "appHome.string_67": { en: "Smart Degassing Sticker", es: "Etiqueta Desgasificadora Inteligente", fr: "Autocollant de Dégazage Intelligent", "zh-TW": "智能排氣貼紙" },
  "appHome.string_68": { en: "Carbon Neutral Bags", es: "Bolsas Neutrales en Carbono", fr: "Sacs Neutres en Carbone", "zh-TW": "碳中和包裝袋" },
  "appHome.string_69": { en: "Spout Pouches Juice", es: "Bolsas con Boquilla para Jugo", fr: "Sachets à Bec pour Jus", "zh-TW": "果汁吸嘴袋" },
  "appHome.string_70": { en: "Child-Resistant Bags", es: "Bolsas a Prueba de Niños", fr: "Sacs à l'Épreuve des Enfants", "zh-TW": "防兒童開啟袋" },
  "appHome.string_71": { en: "Pre-Zippered Rollstock", es: "Bobinas con Cremallera", fr: "Bobines Pré-zippées", "zh-TW": "預置夾鏈卷膜" },
  "appHome.string_72": { en: "Digital Printed Retort", es: "Retorta Impresa Digitalmente", fr: "Cornue Imprimée Numériquement", "zh-TW": "數位印刷蒸煮袋" },
  "appHome.string_73": { en: "Rice Paper Bags", es: "Bolsas de Papel de Arroz", fr: "Sacs en Papier de Riz", "zh-TW": "米紙袋" },
  "appHome.string_74": { en: "PVA Water-Soluble Bags", es: "Bolsas Solubles en Agua de PVA", fr: "Sacs Solubles dans l'Eau PVA", "zh-TW": "PVA 水溶性袋" },
  "appHome.string_75": { en: "compostable Heat-Resistant Pouches", es: "Bolsas Compostables Resistentes al Calor", fr: "Sachets Compostables Résistants à la Chaleur", "zh-TW": "全降解耐熱袋" },
  "appHome.string_76": { en: "Lab Bag", es: "Bolsa de Laboratorio", fr: "Sac de Laboratoire", "zh-TW": "實驗室袋" },
  "appHome.string_77": { en: "Lateral Filter Bags", es: "Bolsas de Filtro Lateral", fr: "Sacs à Filtre Latéral", "zh-TW": "側邊過濾袋" },
  "appHome.string_78": { en: "Wire Closure Bags", es: "Bolsas con Cierre de Alambre", fr: "Sacs à Fermeture en Fil", "zh-TW": "鐵絲密封袋" },
  "appHome.string_79": { en: "Lab Blender Bags", es: "Bolsas de Mezclador de Laboratorio", fr: "Sacs Mélangeurs de Laboratoire", "zh-TW": "實驗室攪拌袋" },
  "appHome.string_80": { en: "Composting", es: "Compostaje", fr: "Compostage", "zh-TW": "堆肥處理" },
  "appHome.string_81": { en: "🌱 Compostable Side Gusset Bags", es: "🌱 Bolsas de Fuelle Lateral Compostables", fr: "🌱 Sacs à Soufflet Latéral Compostables", "zh-TW": "🌱 全降解側邊風琴袋" },
  "appHome.string_82": { en: "Composting Benefits", es: "Beneficios del Compostaje", fr: "Avantages du Compostage", "zh-TW": "堆肥的好處" },
  "appHome.string_83": { en: "Service Finder", es: "Buscador de Servicios", fr: "Recherche de Services", "zh-TW": "服務搜尋器" },
  "appHome.string_84": { en: "Biodegradable vs Compostable", es: "Biodegradable vs Compostable", fr: "Biodégradable vs Compostable", "zh-TW": "生物降解 vs 全降解" },
  "appHome.string_85": { en: "Commercial Composting", es: "Compostaje Comercial", fr: "Compostage Commercial", "zh-TW": "商業堆肥" },
  "appHome.string_86": { en: "Home vs Industrial", es: "Doméstico vs Industrial", fr: "Domestique vs Industriel", "zh-TW": "家庭 vs 工業堆肥" },
  "appHome.string_87": { en: "Plastic-Free vs Compostable", es: "Libre de Plástico vs Compostable", fr: "Sans Plastique vs Compostable", "zh-TW": "無塑料 vs 全降解" },
  "appHome.string_88": { en: "Compost Bag Humidity Control", es: "Control de Humedad en Bolsas de Compost", fr: "Contrôle de l'Humidité des Sacs de Compost", "zh-TW": "全降解袋濕度控制" },
  "appHome.string_89": { en: "Compostable Zipper Durability", es: "Durabilidad de la Cremallera Compostable", fr: "Durabilité de la Fermeture Éclair Compostable", "zh-TW": "全降解夾鏈耐用性" },
  "appHome.string_90": { en: "BioPE", es: "BioPE", fr: "BioPE", "zh-TW": "生物基PE" },
  "appHome.string_91": { en: "What is Bio-PE?", es: "¿Qué es Bio-PE?", fr: "Qu'est-ce que le Bio-PE ?", "zh-TW": "什麼是生物基PE？" },
  "appHome.string_92": { en: "Bio-PE vs Compostable", es: "Bio-PE vs Compostable", fr: "Bio-PE vs Compostable", "zh-TW": "生物基PE vs 全降解" },
  "appHome.string_93": { en: "Bio-PE & EPR", es: "Bio-PE y EPR", fr: "Bio-PE & REP", "zh-TW": "生物基PE 與 EPR" },
  "appHome.string_94": { en: "Inside I'm green™", es: "Inside I'm green™", fr: "Inside I'm green™", "zh-TW": "Inside I'm green™" },
  "appHome.string_95": { en: "What Is PCR Plastic?", es: "¿Qué es el plástico PCR?", fr: "Qu'est-ce que le plastique PCR ?", "zh-TW": "什麼是 PCR 塑料？" },
  "appHome.string_96": { en: "PCR 7-Point Checklist", es: "Lista de Verificación PCR de 7 Puntos", fr: "Liste de Contrôle PCR en 7 Points", "zh-TW": "PCR 7項檢查清單" },
  "appHome.string_97": { en: "Realistic PCR Content", es: "Contenido PCR Realista", fr: "Contenu PCR Réaliste", "zh-TW": "實際 PCR 含量" },
  "appHome.string_98": { en: "Recyclable vs PCR vs Bio-Based", es: "Reciclable vs PCR vs Base Bio", fr: "Recyclable vs PCR vs Biosourcé", "zh-TW": "可回收 vs PCR vs 生物基" },
  "appHome.string_99": { en: "PCR Materials", es: "Materiales PCR", fr: "Matériaux PCR", "zh-TW": "PCR 材料" },
  "appHome.string_100": { en: "What Is 100% Recyclable?", es: "¿Qué es 100% Reciclable?", fr: "Qu'est-ce qui est 100 % recyclable ?", "zh-TW": "什麼是 100% 可回收？" },
  "appHome.string_101": { en: "3-Step SME Roadmap", es: "Hoja de Ruta PYME de 3 Pasos", fr: "Feuille de Route PME en 3 Étapes", "zh-TW": "三步中小企業藍圖" },
  "appHome.string_102": { en: "Mono-Material Foundation", es: "Fundación de Monomateriales", fr: "Base Mono-Matériau", "zh-TW": "單一材質基礎" },
  "appHome.string_103": { en: "Recyclable Mono-PE", es: "Mono-PE Reciclable", fr: "Mono-PE Recyclable", "zh-TW": "可回收 Mono-PE" },
  "appHome.string_104": { en: "Recyclable Mono-PP", es: "Mono-PP Reciclable", fr: "Mono-PP Recyclable", "zh-TW": "可回收 Mono-PP" },
  "appHome.string_105": { en: "Structure Specs", es: "Especificaciones de Estructura", fr: "Spécifications de Structure", "zh-TW": "結構規格" },
  "appHome.string_106": { en: "PCR Structures", es: "Estructuras PCR", fr: "Structures PCR", "zh-TW": "PCR 結構" },
  "appHome.string_107": { en: "Mono PE/PP", es: "Mono PE/PP", fr: "Mono PE/PP", "zh-TW": "單一 PE/PP" },
  "appHome.string_108": { en: "Compostable Bio", es: "Bio Compostable", fr: "Bio Compostable", "zh-TW": "全降解生物基" },
  "appHome.string_109": { en: "Bio-PE Structures", es: "Estructuras Bio-PE", fr: "Structures Bio-PE", "zh-TW": "生物基PE結構" },
  "appHome.string_110": { en: "Trending Topics", es: "Temas de Tendencia", fr: "Sujets Tendances", "zh-TW": "熱門話題" },
  "appHome.string_111": { en: "PFAS-Free Food", es: "Alimentos Libres de PFAS", fr: "Aliments Sans PFAS", "zh-TW": "無 PFAS 食品" },
  "appHome.string_112": { en: "Compostable Coffee", es: "Café Compostable", fr: "Café Compostable", "zh-TW": "全降解咖啡" },
  "appHome.string_113": { en: "Mono-PE Pouches", es: "Bolsas Mono-PE", fr: "Sachets Mono-PE", "zh-TW": "Mono-PE 袋" },
  "appHome.string_114": { en: "Child-Resistant", es: "A Prueba de Niños", fr: "Résistant aux Enfants", "zh-TW": "防兒童開啟" },
  "appHome.string_115": { en: "Ocean Plastic", es: "Plástico del Océano", fr: "Plastique Océanique", "zh-TW": "海洋塑料" },
  "appHome.string_116": { en: "Minimalist D2C", es: "D2C Minimalista", fr: "D2C Minimaliste", "zh-TW": "極簡 D2C" },
  "appHome.string_117": { en: "Unprinted Samples", es: "Muestras Sin Imprimir", fr: "Échantillons Non Imprimés", "zh-TW": "未印刷樣品" },
  "appHome.string_118": { en: "Custom Printed Sample", es: "Muestra Impresa Personalizada", fr: "Échantillon Imprimé Personnalisé", "zh-TW": "客製化印刷樣品" },
  "appHome.string_119": { en: "Customer Reviews", es: "Reseñas de Clientes", fr: "Avis Clients", "zh-TW": "顧客評價" },
  "appHome.string_120": { en: "ryan@achievepack.com", es: "ryan@achievepack.com", fr: "ryan@achievepack.com", "zh-TW": "ryan@achievepack.com" },
  "appHome.string_121": { en: "Blog & Store", es: "Blog y Tienda", fr: "Blog & Boutique", "zh-TW": "部落格與商城" },
  "appHome.string_122": { en: "All Articles", es: "Todos los Artículos", fr: "Tous les Articles", "zh-TW": "所有文章" },
  "appHome.string_123": { en: "Online Store", es: "Tienda en Línea", fr: "Boutique en Ligne", "zh-TW": "線上商城" },
  "appHome.string_124": { en: "Free Services", es: "Servicios Gratuitos", fr: "Services Gratuits", "zh-TW": "免費服務" },
  "appHome.string_125": { en: "Free Design Consultation", es: "Consulta de Diseño Gratuita", fr: "Consultation de Design Gratuite", "zh-TW": "免費設計諮詢" },
  "appHome.string_126": { en: "Free Website Upgrade", es: "Actualización de Sitio Web Gratuita", fr: "Mise à Niveau de Site Web Gratuite", "zh-TW": "免費網站升級" },
  "appHome.string_127": { en: "Free Packaging Mockup", es: "Maqueta de Empaque Gratuita", fr: "Maquette d'Emballage Gratuite", "zh-TW": "免費包裝模擬圖" },
  "appHome.string_128": { en: "Free Customer Center", es: "Centro de Clientes Gratuito", fr: "Centre Client Gratuit", "zh-TW": "免費客戶中心" },
  "appHome.string_129": { en: "Knowledge", es: "Conocimiento", fr: "Connaissances", "zh-TW": "知識庫" },
  "appHome.string_130": { en: "Pouch Sizing Guide", es: "Guía de Tamaños de Bolsas", fr: "Guide des Tailles de Sachets", "zh-TW": "自立袋尺寸指南" },
  "appHome.string_131": { en: "Size Reference", es: "Referencia de Tamaño", fr: "Référence de Taille", "zh-TW": "尺寸參考" },
  "appHome.string_132": { en: "All Options", es: "Todas las Opciones", fr: "Toutes les Options", "zh-TW": "所有選項" },
  "appHome.string_133": { en: "Printing Types", es: "Tipos de Impresión", fr: "Types d'Impression", "zh-TW": "印刷類型" },
  "appHome.string_134": { en: "K-Seal Pouches", es: "Bolsas K-Seal", fr: "Sachets K-Seal", "zh-TW": "K封口袋" },
  "appHome.string_135": { en: "White Ink Underprint", es: "Impresión de Tinta Blanca", fr: "Sous-impression à l'Encre Blanche", "zh-TW": "白墨打底" },
  "appHome.string_136": { en: "Fin vs Lap Seal", es: "Sello de Aleta vs Solapa", fr: "Sceau Fin vs Lap", "zh-TW": "鰭封 vs 搭接封口" },
  "appHome.string_137": { en: "Flat Bottom vs. Side Gusset", es: "Fondo Plano vs Fuelle Lateral", fr: "Fond Plat vs Soufflet Latéral", "zh-TW": "平底 vs 側邊風琴" },
  "appHome.string_138": { en: "BPI & B Corp Certified", es: "Certificado BPI y B Corp", fr: "Certifié BPI & B Corp", "zh-TW": "BPI 與 B 型企業認證" },
  "appHome.string_139": { en: "At Achieve Pack pouch.eco, we contribute 1% of our revenue to carbon removal", es: "En Achieve Pack pouch.eco, contribuimos con el 1% de nuestros ingresos a la eliminación de carbono", fr: "Chez Achieve Pack pouch.eco, nous contribuons à hauteur de 1 % de nos revenus à l'élimination du carbone", "zh-TW": "在 Achieve Pack pouch.eco，我們將 1% 的收入用於碳移除" },
  "appHome.string_140": { en: "Payment Methods", es: "Métodos de Pago", fr: "Modes de Paiement", "zh-TW": "付款方式" },
  "appHome.string_141": { en: "SSL 100% Secure Transactions", es: "Transacciones SSL 100% Seguras", fr: "Transactions SSL 100% Sécurisées", "zh-TW": "SSL 100% 安全交易" },
  "appHome.string_142": { en: "Connect with us", es: "Conecta con nosotros", fr: "Connectez-vous avec nous", "zh-TW": "與我們聯繫" },
  "appHome.string_143": { en: "Enlarged view", es: "Vista Ampliada", fr: "Vue Agrandie", "zh-TW": "放大預覽" },
  "appHome.string_144": { en: "reviews)", es: "reseñas)", fr: "avis)", "zh-TW": "則評價)" },
  "appHome.string_145": { en: "US$", es: "US$", fr: "US$", "zh-TW": "US$" },
  "appHome.string_146": { en: "for", es: "por", fr: "pour", "zh-TW": "為" },
  "appHome.string_147": { en: "pcs", es: "uds", fr: "pcs", "zh-TW": "件" },
  "appHome.string_148": { en: "Features", es: "Características", fr: "Caractéristiques", "zh-TW": "特色" },
  "appHome.string_149": { en: "In Stock", es: "En Stock", fr: "En Stock", "zh-TW": "現貨" },
  "appHome.string_150": { en: "Add to Cart", es: "Añadir al Carrito", fr: "Ajouter au Panier", "zh-TW": "加入購物車" },
  "appHome.string_151": { en: "Explore More", es: "Explorar Más", fr: "Explorer Plus", "zh-TW": "探索更多" },
  "appHome.string_152": { en: "Ryan Wong", es: "Ryan Wong", fr: "Ryan Wong", "zh-TW": "Ryan Wong" },
  "appHome.string_153": { en: "Packaging Development Specialist", es: "Especialista en Desarrollo de Empaques", fr: "Spécialiste en Développement d'Emballages", "zh-TW": "包裝開發專家" },
  "appHome.string_154": { en: "14 years experience | 8 countries | Fortune 500 & DTC startups", es: "14 años de experiencia | 8 países | Fortune 500 y Startups DTC", fr: "14 ans d'expérience | 8 pays | Fortune 500 et startups DTC", "zh-TW": "14年經驗 | 8個國家 | 財富500強與DTC初創企業" },
  "appHome.string_155": { en: "🎓 The Hong Kong Polytechnic University (Honor Degree)", es: "🎓 Universidad Politécnica de Hong Kong (Título de Honor)", fr: "🎓 Université Polytechnique de Hong Kong (Diplôme d'Honneur)", "zh-TW": "🎓 香港理工大學 (榮譽學位)" },
  "appHome.string_156": { en: "Ryan Wong at Packaging Exhibition", es: "Ryan Wong en Exhibición de Empaques", fr: "Ryan Wong au Salon de l'Emballage", "zh-TW": "Ryan Wong 在包裝展覽" },
  "appHome.string_157": { en: "Ryan at international packaging exhibition", es: "Ryan en exhibición internacional de empaques", fr: "Ryan au salon international de l'emballage", "zh-TW": "Ryan 在國際包裝展覽" },
  "appHome.string_158": { en: "About Ryan", es: "Sobre Ryan", fr: "À propos de Ryan", "zh-TW": "關於 Ryan" },
  "appHome.string_159": { en: "With", es: "Con", fr: "Avec", "zh-TW": "擁有" },
  "appHome.string_160": { en: "14 years of dedicated experience", es: "14 años de experiencia dedicada", fr: "14 années d'expérience dédiée", "zh-TW": "14年的專注經驗" },
  "appHome.string_161": { en: "in the packaging industry, Ryan Wong has built expertise cooperating with multinational and Fortune 500 companies to achieve mutual beneficial and long-lasting business relationships.", es: "en la industria del empaque, Ryan Wong ha desarrollado experiencia cooperando con empresas multinacionales y Fortune 500 para lograr relaciones comerciales duraderas y mutuamente beneficiosas.", fr: "dans l'industrie de l'emballage, Ryan Wong a acquis une expertise en coopérant avec des entreprises multinationales et Fortune 500 pour établir des relations commerciales durables et mutuellement bénéfiques.", "zh-TW": "在包裝行業中，Ryan Wong 累積了與跨國及財富500強企業合作的專業知識，建立互惠互利且長久的商業關係。" },
  "appHome.string_162": { en: "Ryan's packaging experience and business relationships span", es: "La experiencia en empaques y las relaciones comerciales de Ryan abarcan", fr: "L'expérience en emballage et les relations commerciales de Ryan couvrent", "zh-TW": "Ryan 的包裝經驗與商業人脈橫跨" },
  "appHome.string_163": { en: "8 countries", es: "8 países", fr: "8 pays", "zh-TW": "8 個國家" },
  "appHome.string_164": { en: ": Australia, Canada, China, Germany, South Africa, Philippines, UK and USA. As a", es: ": Australia, Canadá, China, Alemania, Sudáfrica, Filipinas, Reino Unido y EE. UU. Como un", fr: ": Australie, Canada, Chine, Allemagne, Afrique du Sud, Philippines, Royaume-Uni et États-Unis. En tant que", "zh-TW": "：澳洲、加拿大、中國、德國、南非、菲律賓、英國和美國。作為一名" },
  "appHome.string_165": { en: "Hong Kong Polytechnic University Honor Degree", es: "Graduado con Título de Honor de la Universidad Politécnica de Hong Kong", fr: "Diplômé avec distinction de l'Université Polytechnique de Hong Kong", "zh-TW": "香港理工大學榮譽學位" },
  "appHome.string_166": { en: "graduate in Global Supply Chain and Business Administration, he combines academic excellence with practical expertise.", es: "en Cadena de Suministro Global y Administración de Empresas, combina excelencia académica con experiencia práctica.", fr: "en Chaîne d'Approvisionnement Mondiale et Administration des Affaires, il combine excellence académique et expertise pratique.", "zh-TW": "全球供應鏈與工商管理畢業生，他將學術卓越與實踐專業相結合。" },
  "appHome.string_167": { en: "At Achieve Pack, Ryan specializes in", es: "En Achieve Pack, Ryan se especializa en", fr: "Chez Achieve Pack, Ryan se spécialise dans", "zh-TW": "在 Achieve Pack，Ryan 專精於" },
  "appHome.string_168": { en: "100% compostable digital print solutions", es: "Soluciones de impresión digital 100% compostables", fr: "Solutions d'impression numérique 100 % compostables", "zh-TW": "100% 全降解數位印刷解決方案" },
  "appHome.string_169": { en: "with industry-leading low MOQ (100-500 pieces), making sustainable packaging accessible to DTC startups and established brands alike.", es: "con un MOQ bajo líder en la industria (100-500 piezas), haciendo que el empaque sostenible sea accesible tanto para startups DTC como para marcas establecidas.", fr: "avec un faible MOQ leader de l'industrie (100-500 pièces), rendant l'emballage durable accessible aux startups DTC et aux marques établies.", "zh-TW": "憑藉業界領先的低起訂量（100-500 件），讓 DTC 初創企業和成熟品牌都能輕鬆使用可持續包裝。" },
  "appHome.string_170": { en: "Core Expertise", es: "Experiencia Central", fr: "Expertise Principale", "zh-TW": "核心專長" },
  "appHome.string_171": { en: "Years Experience", es: "Años de Experiencia", fr: "Années d'Expérience", "zh-TW": "年經驗" },
  "appHome.string_172": { en: "Countries Served", es: "Países Atendidos", fr: "Pays Desservis", "zh-TW": "服務國家" },
  "appHome.string_173": { en: "Minimum Order", es: "Pedido Mínimo", fr: "Commande Minimale", "zh-TW": "最低訂購量" },
  "appHome.string_174": { en: "Days Rush", es: "Días de Prisa", fr: "Jours Urgents", "zh-TW": "天急件" },
  "appHome.string_175": { en: "LinkedIn Profile", es: "Perfil de LinkedIn", fr: "Profil LinkedIn", "zh-TW": "LinkedIn 個人資料" },
  "appHome.string_176": { en: "Contact", es: "Contacto", fr: "Contact", "zh-TW": "聯絡我們" },
  "appHome.string_177": { en: "Schedule Meeting", es: "Programar Reunión", fr: "Planifier une Réunion", "zh-TW": "預約會議" },
  "appHome.string_178": { en: "View Full Profile", es: "Ver Perfil Completo", fr: "Voir el Profil Complet", "zh-TW": "查看完整個人資料" }
};
